### ISSUE TITLE
Collision system is primitive, disorganized, and hard to understand.

### ISSUE THREAD

**Issue by gvJaime** [elgambitero/SOI_MD#4]
The system that calculates the block indexes for collisions, block creation, and general environment interaction is comprised by a batch of static inline functions that contain the same code, with obnoxious suffixes.

The system, block index variables, and functions; could be ported to a buffer based one, with a single function to fill any position of the buffer.

The buffer could comprise the index of the block in contact with the four corners for the bounding box, and the center of the four edges, as well as the center. Indexes should be macros for readability.

**Comment by elgambitero** [comment]
Settled for bulk checking, but only when the sprite collision flag has been triggered
